def custom_css():
    custom_css = """
        <style>
            /* Targeting the div elements generated by st.write */
            div.stMarkdown > div {
                font-size: 24px;  /* Custom font size */
                font-family: 'Arial', sans-serif;  /* Custom font family */
                color: blue;  /* Custom font color */
            }
            /* Targeting all textarea elements */
            .element-container:has(>.stTextArea), .stTextArea {
                width: 800px !important;
            }
            .stTextArea textarea {
                height: 400px;
            }
            /* Styling for the first button */
            div.stButton > button:first-child {
                width: 250px;
                height: 100px;
                border-radius: 10px; /* Rounded corners */
                background-color: #3f60b9; /* Background color */
                box-shadow: 1px 1px 1px grey; /* Shadow effect */
            }
            /* Hover effect for the first button */
            div.stButton > button:first-child:hover {
                background-color: #01ff56; /* Color changes on hover */
            }
            /* Styling for the second button */
            div.stButton > button:nth-child(2) {
                width: 250px;
                height: 100px;
                border-radius: 10px;
                background-color: #3f60b9;
                box-shadow: 1px 1px 1px grey;
            }
            /* Hover effect for the second button */
            div.stButton > button:nth-child(2):hover {
                background-color: #01ff56;
            }
            /* Additional styles for radio buttons */
            div.row-widget.stRadio > div {
                flex-direction: row;
                align-items: stretch;
            }
            div.row-widget.stRadio > div[role="radiogroup"] > label[data-baseweb="radio"] > div:first-child {
                display: none;
            }
            div.row-widget.stRadio > div[role="radiogroup"] > label[data-baseweb="radio"] {
                background: transparent;
                font-size: 24px;
                padding-right: 10px;
                padding-left: 4px;
                padding-bottom: 3px;
                margin: 4px;
                border: 1px solid #249ded;
            }
            input[type="radio"]:checked + label[data-baseweb="radio"] {
                background: red !important;
            }
        </style>
    """            

    return custom_css

